apiVersion: apps/v1
kind: Deployment
metadata:
  name: spandaai-backend
  labels:
    app: spandaai-backend
    app.kubernetes.io/name: spandaai-backend
    app.kubernetes.io/part-of: spandaai-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spandaai-backend
  template:
    metadata:
      labels:
        app: spandaai-backend
        app.kubernetes.io/name: spandaai-backend
        app.kubernetes.io/part-of: spandaai-platform
    spec:
      containers:
      - name: backend
        image: your-registry/spanda-backend:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: spandaai-backend-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: spandaai-backend-secrets
              key: jwt-secret
        - name: CORS_ORIGIN
          value: "https://spandaai.local"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
