apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spandaai-backend-secrets
  labels:
    app: spandaai-backend
    app.kubernetes.io/name: spandaai-backend
    app.kubernetes.io/part-of: spandaai-platform
spec:
  encryptedData:
    # These are example encrypted values - replace with actual sealed secrets
    # Use: echo -n "your-actual-database-url" | kubeseal --raw --from-file=/dev/stdin --name=spandaai-backend-secrets --namespace=spandaai-backend
    database-url: AgBy3i4OJSWK+PiTySYZZA9rO5QtQUmYMcOBs4N1dX...  # Replace with actual encrypted value
    jwt-secret: AgAh5gH7tnK+Px8TySYZZA9rO5QtQUmYMcOBs4N1dX...     # Replace with actual encrypted value
  template:
    metadata:
      name: spandaai-backend-secrets
      labels:
        app: spandaai-backend
        app.kubernetes.io/name: spandaai-backend
        app.kubernetes.io/part-of: spandaai-platform
    type: Opaque

---
# Alternative: Use regular Secret for development (NOT for production)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: spandaai-backend-secrets-dev
#   labels:
#     app: spandaai-backend
#     app.kubernetes.io/name: spandaai-backend
#     app.kubernetes.io/part-of: spandaai-platform
# type: Opaque
# data:
#   # Base64 encoded values - replace with actual values
#   database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi5leGFtcGxlLmNvbTo1NDMyL215ZGI=  # postgresql://user:pass@db.example.com:5432/mydb
#   jwt-secret: bXlfc3VwZXJfc2VjcmV0X2p3dF9rZXk=  # my_super_secret_jwt_key
