# GitHub Actions Workflow Template for test-application
# Copy this file to your application repository at: .github/workflows/deploy-gitops.yml

name: Build and Deploy test-application

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '*.md'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  call-platform-workflow:
    name: Deploy via Platform Workflow
    uses: aryan-spanda/spandaai-workflows/.github/workflows/build-and-deploy.yml@main
    with:
      app-name: "test-application"
      dockerfile-path: "Dockerfile"
      docker-context: "."
      helm-chart-path: "apps/test-application"
      config-repo: "aryan-spanda/config-repo"
      platform-requirements-file: "platform-requirements.yml"
      # Application-specific settings
      frontend-enabled: "true"
      backend-enabled: "true"
      primary-port: "3000"
      health-check-path: "/"
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONFIG_REPO_PAT: ${{ secrets.CONFIG_REPO_PAT }}
