# Production values for test-application
replicaCount: 2

image:
  repository: ghcr.io/aryan-spanda/test-application
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

ingress:
  hosts:
    - host: app.example.com
      paths:
        - path: /api(/|\$)(.*)
          pathType: Prefix
  tls:
    - secretName: test-application-prod-tls
      hosts:
        - app.example.com

# Production-specific settings
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Environment variables for production
env:
  - name: NODE_ENV
    value: "production"
  - name: REACT_APP_API_URL
    value: "https://app.example.com/api"

