apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      prefix: docker.io
      ping: yes
      default: yes
      
  argocd.conf: |
    argocd.server_addr: argocd-server.argocd.svc.cluster.local:443
    argocd.insecure: false
    argocd.grpc_web: true
    
  log.level: "info"
  interval: "600s"  # Check every 10 minutes - more conservative
  kube.events: "true"
  kube.events.namespace: "argocd"
  git.commit.signing-key: ""
  git.commit.signing-method: ""
  # Conservative settings to prevent update loops
  applicationimageupdate.enabled: "true"
  argocd.allow_concurrency: "false"  # Prevent race conditions
  metrics.enabled: "true"
  # Only commit when there are actual changes
  git.commit.message-template: |
    build: automatic update of {{.AppName}}
    
    {{range .AppChanges -}}
    Updates {{.Image}} tag '{{.OldTag}}' to '{{.NewTag}}'
    {{end -}}
