apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spandaai-platform-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: spandaai-platform-bootstrap
    app.kubernetes.io/part-of: spandaai-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/aryan-spanda/Spanda-config.git
    targetRevision: HEAD
    path: landing-zone/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
  revisionHistoryLimit: 3
