apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-application
    app.kubernetes.io/part-of: spandaai-platform
    team: development-team
    environment: staging
    app-type: fullstack
  annotations:
    app.spanda.ai/generated: "true"
    app.spanda.ai/generator: "platform-automation"
    app.spanda.ai/generated-at: "2025-08-05T07:40:11Z"
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: test-app=ghcr.io/aryan-spanda/test-application
    argocd-image-updater.argoproj.io/test-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/test-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/test-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/test-app.allow-tags: regexp:^testing-[0-9a-f]{7,8}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:values-staging.yaml"
spec:
  project: spanda-applications
  source:
    repoURL: https://github.com/aryan-spanda/Test-Application.git
    targetRevision: testing
    path: deploy/helm
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/aryan-spanda/test-application
        - name: image.tag
          value: testing-placeholder
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: 'Generated By'
      value: 'Platform Automation'
    - name: 'Source Repository'
      value: 'https://github.com/aryan-spanda/Test-Application.git'
    - name: 'Chart Path'
      value: 'deploy/helm'
    - name: 'Environment'
      value: 'staging'
    - name: 'Team'
      value: 'development-team'
    - name: 'Application Type'
      value: 'fullstack'
