apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-application
    app.kubernetes.io/part-of: spandaai-platform
    team: spanda-team
    environment: production
spec:
  project: spandaai-platform
  source:
    repoURL: https://github.com/aryan-spanda/Test-Application.git
    targetRevision: main
    path: deploy/helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10

---
# Template for new applications
# Replace the following placeholders:
# 1. metadata.name: test-application -> your-app-name
# 2. source.repoURL: https://github.com/aryan-spanda/Test-Application.git -> your-repo-url
# 3. source.path: deploy/helm -> path-to-your-manifests
# 4. destination.namespace: test-application -> your-app-namespace
# 5. labels.team: spanda-team -> your-team-name
