apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application-prod
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: test-app=ghcr.io/aryan-spanda/test-application
    argocd-image-updater.argoproj.io/test-app.update-strategy: latest
    argocd-image-updater.argoproj.io/test-app.allow-tags: regexp:^(latest|main-.+)$
    argocd-image-updater.argoproj.io/test-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/test-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  labels:
    app.kubernetes.io/name: test-application
    app.kubernetes.io/part-of: spandaai-platform
    team: spanda-team
    environment: production
spec:
  project: spandaai-platform
  source:
    repoURL: https://github.com/aryan-spanda/config-repo.git
    targetRevision: main
    path: apps/test-application
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
