apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spandaai-backend-production

namespace: spandaai-backend

resources:
- ../../base

patchesStrategicMerge:
- replicas.yaml
- ingress-patch.yaml

commonLabels:
  app.kubernetes.io/environment: production

images:
- name: your-registry/spanda-backend
  newTag: v1.0.0  # This will be updated by CI/CD or Image Updater
