#!/bin/bash

# 🏗️ Spanda Platform - Client Application Onboarding Script
# This script is used by the PLATFORM TEAM to onboard new applications
# It creates all deployment configuration in the Spanda-config repository

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[PLATFORM]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in the config repository
if [ ! -f "scripts/generate-app-manifests.sh" ]; then
    print_error "This script must be run from the Spanda-config repository root"
    exit 1
fi

echo "🏗️ Spanda Platform - Client Application Onboarding"
echo "================================================="
echo "This script onboards a new client application to the platform."
echo ""

# Collect application information
read -p "📝 Application name (lowercase, no spaces): " APP_NAME
read -p "🔗 Client repository URL: " REPO_URL
read -p "📧 Client contact email: " CLIENT_EMAIL
read -p "🏷️  Environment (staging/production): " ENVIRONMENT
read -p "🐳 Client Docker registry (e.g., ghcr.io/username): " DOCKER_REGISTRY
read -p "🔌 Application port (default: 3000): " APP_PORT
read -p "💾 Resource size (small/medium/large, default: medium): " RESOURCE_SIZE

# Set defaults
APP_PORT=${APP_PORT:-3000}
RESOURCE_SIZE=${RESOURCE_SIZE:-medium}
ENVIRONMENT=${ENVIRONMENT:-staging}

# Validate inputs
if [[ -z "$APP_NAME" || -z "$REPO_URL" || -z "$CLIENT_EMAIL" || -z "$DOCKER_REGISTRY" ]]; then
    print_error "Required fields cannot be empty"
    exit 1
fi

# Clean app name
APP_NAME_CLEAN=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

echo ""
print_status "Creating platform configuration for: $APP_NAME_CLEAN"
echo ""

# Create ArgoCD application manifest
ARGOCD_APP_DIR="landing-zone/applications"
mkdir -p "$ARGOCD_APP_DIR"

print_status "Creating ArgoCD application manifest..."

cat > "$ARGOCD_APP_DIR/${APP_NAME_CLEAN}-${ENVIRONMENT}.yaml" << EOF
# ArgoCD Application for ${APP_NAME_CLEAN}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Client: $CLIENT_EMAIL

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${APP_NAME_CLEAN}-${ENVIRONMENT}
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: ${APP_NAME_CLEAN}=${DOCKER_REGISTRY}/${APP_NAME_CLEAN}
    argocd-image-updater.argoproj.io/${APP_NAME_CLEAN}.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd.argoproj.io/sync-wave: "5"
    
    # Client metadata
    platform.spandaai.com/client-email: "${CLIENT_EMAIL}"
    platform.spandaai.com/onboarded-date: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    platform.spandaai.com/resource-size: "${RESOURCE_SIZE}"
    
  labels:
    app.kubernetes.io/name: ${APP_NAME_CLEAN}
    app.kubernetes.io/part-of: spandaai-platform
    environment: ${ENVIRONMENT}
    client-managed: "true"
    
spec:
  project: spandaai-platform
  source:
    repoURL: ${REPO_URL}
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${APP_NAME_CLEAN}-${ENVIRONMENT}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5
EOF

print_success "ArgoCD application created: $ARGOCD_APP_DIR/${APP_NAME_CLEAN}-${ENVIRONMENT}.yaml"

# Create Helm chart for the application
HELM_CHART_DIR="apps/${APP_NAME_CLEAN}"
mkdir -p "$HELM_CHART_DIR"

print_status "Creating Helm chart..."

# Create Chart.yaml
cat > "$HELM_CHART_DIR/Chart.yaml" << EOF
apiVersion: v2
name: ${APP_NAME_CLEAN}
description: Helm chart for ${APP_NAME_CLEAN}
version: 1.0.0
appVersion: "latest"
maintainers:
  - name: Spanda Platform Team
    email: platform@spandaai.com
annotations:
  platform.spandaai.com/client-email: "${CLIENT_EMAIL}"
  platform.spandaai.com/onboarded-date: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF

# Create values.yaml with appropriate resource sizing
case $RESOURCE_SIZE in
  small)
    CPU_REQUEST="250m"
    MEMORY_REQUEST="256Mi"
    CPU_LIMIT="500m"
    MEMORY_LIMIT="512Mi"
    REPLICAS="1"
    ;;
  large)
    CPU_REQUEST="1000m"
    MEMORY_REQUEST="1Gi"
    CPU_LIMIT="2000m"
    MEMORY_LIMIT="2Gi"
    REPLICAS="3"
    ;;
  *)
    CPU_REQUEST="500m"
    MEMORY_REQUEST="512Mi"
    CPU_LIMIT="1000m"
    MEMORY_LIMIT="1Gi"
    REPLICAS="2"
    ;;
esac

cat > "$HELM_CHART_DIR/values.yaml" << EOF
# Helm values for ${APP_NAME_CLEAN}
# Generated by Spanda Platform Team
# Client: $CLIENT_EMAIL

replicaCount: $REPLICAS

image:
  repository: ${DOCKER_REGISTRY}/${APP_NAME_CLEAN}
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automountServiceAccountToken: false
  annotations: {}

podSecurityContext:
  fsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 80
  targetPort: $APP_PORT

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ${APP_NAME_CLEAN}-${ENVIRONMENT}.spandaai.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ${APP_NAME_CLEAN}-${ENVIRONMENT}-tls
      hosts:
        - ${APP_NAME_CLEAN}-${ENVIRONMENT}.spandaai.com

resources:
  limits:
    cpu: ${CPU_LIMIT}
    memory: ${MEMORY_LIMIT}
  requests:
    cpu: ${CPU_REQUEST}
    memory: ${MEMORY_REQUEST}

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: $REPLICAS
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Spanda Platform specific configuration
platform:
  monitoring:
    enabled: true
    serviceMonitor:
      enabled: true
      path: /metrics
      interval: 30s
  
  security:
    networkPolicy:
      enabled: true
    podSecurityPolicy:
      enabled: true

# Client metadata
client:
  email: "${CLIENT_EMAIL}"
  onboardedDate: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  resourceSize: "${RESOURCE_SIZE}"
EOF

# Create Kubernetes templates directory
TEMPLATES_DIR="$HELM_CHART_DIR/templates"
mkdir -p "$TEMPLATES_DIR"

# Create deployment template
cat > "$TEMPLATES_DIR/deployment.yaml" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
EOF

# Create service template
cat > "$TEMPLATES_DIR/service.yaml" << 'EOF'
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
EOF

# Create ingress template
cat > "$TEMPLATES_DIR/ingress.yaml" << 'EOF'
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
EOF

# Create helpers template
cat > "$TEMPLATES_DIR/_helpers.tpl" << 'EOF'
{{/*
Expand the name of the chart.
*/}}
{{- define "chart.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "chart.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "chart.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "chart.labels" -}}
helm.sh/chart: {{ include "chart.chart" . }}
{{ include "chart.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "chart.selectorLabels" -}}
app.kubernetes.io/name: {{ include "chart.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "chart.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "chart.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
EOF

print_success "Helm chart created: $HELM_CHART_DIR/"

# Update monitoring configuration
print_status "Updating monitoring configuration..."

PROMETHEUS_CONFIG="cluster-config/monitoring/prometheus.yaml"
if [ -f "$PROMETHEUS_CONFIG" ]; then
    # Add scrape config for new application (simplified version)
    echo "  # Auto-added for ${APP_NAME_CLEAN}-${ENVIRONMENT}" >> "$PROMETHEUS_CONFIG"
    echo "  - job_name: '${APP_NAME_CLEAN}-${ENVIRONMENT}'" >> "$PROMETHEUS_CONFIG"
    echo "    kubernetes_sd_configs:" >> "$PROMETHEUS_CONFIG"
    echo "    - role: endpoints" >> "$PROMETHEUS_CONFIG"
    echo "    relabel_configs:" >> "$PROMETHEUS_CONFIG"
    echo "    - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]" >> "$PROMETHEUS_CONFIG"
    echo "      action: keep" >> "$PROMETHEUS_CONFIG"
    echo "      regex: ${APP_NAME_CLEAN}" >> "$PROMETHEUS_CONFIG"
    echo "    - source_labels: [__meta_kubernetes_namespace]" >> "$PROMETHEUS_CONFIG"
    echo "      action: keep" >> "$PROMETHEUS_CONFIG"
    echo "      regex: ${APP_NAME_CLEAN}-${ENVIRONMENT}" >> "$PROMETHEUS_CONFIG"
    echo "" >> "$PROMETHEUS_CONFIG"
    
    print_success "Monitoring configuration updated"
else
    print_warning "Prometheus configuration not found, skipping monitoring setup"
fi

# Generate client notification
CLIENT_NOTIFICATION="onboarding-complete-${APP_NAME_CLEAN}.md"

cat > "$CLIENT_NOTIFICATION" << EOF
# 🎉 Application Onboarding Complete!

**Application:** $APP_NAME_CLEAN  
**Environment:** $ENVIRONMENT  
**Client:** $CLIENT_EMAIL  
**Onboarded:** $(date)

## What We've Created

### ✅ ArgoCD Application
- **File:** \`landing-zone/applications/${APP_NAME_CLEAN}-${ENVIRONMENT}.yaml\`
- **Purpose:** Manages your application deployment
- **Auto-sync:** Enabled (your app will auto-deploy on code changes)

### ✅ Helm Chart
- **Location:** \`apps/${APP_NAME_CLEAN}/\`
- **Resources:** $RESOURCE_SIZE (CPU: $CPU_REQUEST-$CPU_LIMIT, Memory: $MEMORY_REQUEST-$MEMORY_LIMIT)
- **Replicas:** $REPLICAS
- **Health checks:** Configured for /health endpoint

### ✅ Ingress Configuration
- **URL:** https://${APP_NAME_CLEAN}-${ENVIRONMENT}.spandaai.com
- **SSL:** Automatic (Let's Encrypt)
- **Load balancer:** Nginx Ingress

### ✅ Monitoring
- **Prometheus:** Configured to scrape /metrics endpoint
- **Grafana:** Dashboards available
- **Alerts:** Basic alerts configured

## Next Steps for Client

1. **Ensure your application has required endpoints:**
   - \`GET /health\` - Must return 200 when healthy
   - \`GET /metrics\` - Prometheus metrics (optional)

2. **Push your Docker images to:** $DOCKER_REGISTRY/$APP_NAME_CLEAN

3. **Your application will be accessible at:**
   - https://${APP_NAME_CLEAN}-${ENVIRONMENT}.spandaai.com

## Support

- **Platform Team:** platform@spandaai.com
- **Monitoring:** https://monitoring.spandaai.com
- **Documentation:** https://docs.spandaai.com

Welcome to Spanda Platform! 🚀
EOF

print_success "Client notification created: $CLIENT_NOTIFICATION"

echo ""
print_success "✅ Application onboarding complete!"
echo ""
echo "📋 Summary:"
echo "  • ArgoCD application: $ARGOCD_APP_DIR/${APP_NAME_CLEAN}-${ENVIRONMENT}.yaml"
echo "  • Helm chart: $HELM_CHART_DIR/"
echo "  • Monitoring: Updated"
echo "  • Client notification: $CLIENT_NOTIFICATION"
echo ""
echo "🔄 Next steps:"
echo "1. Review the generated files"
echo "2. Commit and push changes to config repository:"
echo "   git add ."
echo "   git commit -m \"Onboard ${APP_NAME_CLEAN}-${ENVIRONMENT}\""
echo "   git push origin main"
echo ""
echo "3. Send client notification to: $CLIENT_EMAIL"
echo "4. Application will be available at: https://${APP_NAME_CLEAN}-${ENVIRONMENT}.spandaai.com"
echo ""
print_success "Client successfully onboarded to Spanda Platform! 🎉"
