# Platform module mappings - defines which Helm charts to deploy for each platform requirement
platform_modules:
  # Address management (MetalLB + External-DNS)
  address_management:
    enabled: true
    chart_path: "bare-metal/modules/net-address-baremetal/helm"
    namespace: "platform-networking"
    priority: 1
    description: "MetalLB and External-DNS address management"

  # VPC networking
  vpc_networking:
    enabled: true
    chart_path: "bare-metal/modules/net-vpc-baremetal/helm"
    namespace: "platform-networking"
    priority: 1
    description: "VPC networking configuration for bare metal"
  
  # External load balancer
  external_load_balancer:
    enabled: true
    chart_path: "bare-metal/modules/net-lb-app-external-baremetal/helm"
    namespace: "platform-networking"
    priority: 2
    depends_on: ["vpc_networking"]
    description: "External load balancer for applications"
  
  # Internal load balancer
  internal_load_balancer:
    enabled: true
    chart_path: "bare-metal/modules/net-lb-app-internal-baremetal/helm"
    namespace: "platform-networking"
    priority: 2
    depends_on: ["vpc_networking"]
    description: "Internal load balancer for applications"
  
  # Firewall and security
  firewall:
    enabled: true
    chart_path: "bare-metal/modules/net-firewall-baremetal/helm"
    namespace: "platform-security"
    priority: 3
    depends_on: ["vpc_networking"]
    description: "Firewall and security rules"

  # Additional load balancer (general purpose)
  load_balancer:
    enabled: true
    chart_path: "bare-metal/modules/net-lb-baremetal/helm"
    namespace: "platform-networking"
    priority: 2
    depends_on: ["vpc_networking"]
    description: "General purpose load balancer"

