apiVersion: apps/v1
kind: Deployment
metadata:
  name: spandaai-backend
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: CORS_ORIGIN
          value: "https://app.spandaai.com"
